name: Deploy to Firebase Hosting on Merge

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Firebase service account key
        run: echo "$FIREBASE_SERVICE_ACCOUNT_KEY" > service-account-key.json
      
      - name: Set up Google Application Credentials
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ./service-account-key.json
        run: echo "$GOOGLE_APPLICATION_CREDENTIALS" > $GITHUB_ENV
      
      - name: Deploy to Firebase Hosting
        run: firebase deploy --only hosting
